// <auto-generated />
using System;
using ArizaSikayet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArizaSikayet.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260519093320_RemovePersonelUniqueCode")]
    partial class RemovePersonelUniqueCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("ArizaSikayet.Models.Ariza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresTarifi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double>("Boylam")
                        .HasColumnType("REAL");

                    b.Property<bool>("CozulduMu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Enlem")
                        .HasColumnType("REAL");

                    b.Property<string>("FotografYolu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VatandasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VatandasId");

                    b.ToTable("Arizalar");
                });

            modelBuilder.Entity("ArizaSikayet.Models.EngellenenEposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("EngellenenEpostalar");
                });

            modelBuilder.Entity("ArizaSikayet.Models.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("GorevKategori")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreSifirlamaToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SifreSifirlamaTokenTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("ArizaSikayet.Models.PersonelKayitIstegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("GorevKategori")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("KayitTamamlamaToken")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("KayitTamamlamaTokenKullanildi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SonucTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PersonelKayitIstekleri");
                });

            modelBuilder.Entity("ArizaSikayet.Models.Vatandas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EpostaOnaylandi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KayitOnayToken")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("KayitOnayTokenKullanildi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreSifirlamaToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SifreSifirlamaTokenTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("Vatandaslar");
                });

            modelBuilder.Entity("ArizaSikayet.Models.Ariza", b =>
                {
                    b.HasOne("ArizaSikayet.Models.Vatandas", "Vatandas")
                        .WithMany("Arizalar")
                        .HasForeignKey("VatandasId");

                    b.Navigation("Vatandas");
                });

            modelBuilder.Entity("ArizaSikayet.Models.Vatandas", b =>
                {
                    b.Navigation("Arizalar");
                });
#pragma warning restore 612, 618
        }
    }
}
