// <auto-generated />
using System;
using ArizaSikayet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArizaSikayet.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20260512190739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Ariza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Boylam")
                        .HasColumnType("REAL");

                    b.Property<bool>("CozulduMu")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Enlem")
                        .HasColumnType("REAL");

                    b.Property<string>("FotografYolu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arizalar");
                });
#pragma warning restore 612, 618
        }
    }
}
